// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6y_m4FfvE56_MOxknsmHOADwyY8Ru4HU',
    appId: '1:758349970982:web:0fe9e1ea3ab5852cb6b0e7',
    messagingSenderId: '758349970982',
    projectId: 'task-mgmt-842e0',
    authDomain: 'task-mgmt-842e0.firebaseapp.com',
    storageBucket: 'task-mgmt-842e0.firebasestorage.app',
    measurementId: 'G-JYLM19VWX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc3jBS7EynrMIyDLm9we8sRq88WJ88mPY',
    appId: '1:758349970982:android:f1574c74f94ab5eeb6b0e7',
    messagingSenderId: '758349970982',
    projectId: 'task-mgmt-842e0',
    storageBucket: 'task-mgmt-842e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF6Iu3t5e9iJ-5ZRROpS1OjyRt9DKAIF8',
    appId: '1:758349970982:ios:8055f48526f1a78db6b0e7',
    messagingSenderId: '758349970982',
    projectId: 'task-mgmt-842e0',
    storageBucket: 'task-mgmt-842e0.firebasestorage.app',
    iosBundleId: 'com.example.taskMgmt02',
  );

}